version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: plantes
      MARIADB_ROOT_PASSWORD:
      MARIADB_USER: root
    volumes:
      - db-data:/var/lib/mariadb/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
